// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCftAvVJ3RR9wHbXr4ZMJVD9VyVT0BGjG0',
    appId: '1:525215714726:web:7cb12f804c63ab41715367',
    messagingSenderId: '525215714726',
    projectId: 'battledraft-9f3ce',
    authDomain: 'battledraft-9f3ce.firebaseapp.com',
    databaseURL: 'https://battledraft-9f3ce-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'battledraft-9f3ce.appspot.com',
    measurementId: 'G-W9E28ZLS67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU-U0WP_tP9IfZyzAeC83agXyHmOabrHo',
    appId: '1:525215714726:android:4897b2f20f06f3fb715367',
    messagingSenderId: '525215714726',
    projectId: 'battledraft-9f3ce',
    databaseURL: 'https://battledraft-9f3ce-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'battledraft-9f3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwV3fap9YfRiKRQ5gBmA96omiXoqR6axY',
    appId: '1:525215714726:ios:f376cf307f78cedb715367',
    messagingSenderId: '525215714726',
    projectId: 'battledraft-9f3ce',
    databaseURL: 'https://battledraft-9f3ce-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'battledraft-9f3ce.appspot.com',
    iosClientId: '525215714726-52u38cvl1iahgbvh587a17v9pgeln317.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwV3fap9YfRiKRQ5gBmA96omiXoqR6axY',
    appId: '1:525215714726:ios:f376cf307f78cedb715367',
    messagingSenderId: '525215714726',
    projectId: 'battledraft-9f3ce',
    databaseURL: 'https://battledraft-9f3ce-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'battledraft-9f3ce.appspot.com',
    iosClientId: '525215714726-52u38cvl1iahgbvh587a17v9pgeln317.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
